niiph_admin_label:
    resource: |
        alias: niiph_product_label.label
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['show']
        redirect: update
        grid: niiph_admin_label
        permission: true
        vars:
            all:
                header: niiph_product_label.ui.label_header
                subheader: niiph_product_label.ui.label_subheader
                templates:
                    form: "@NiiphSyliusProductLabelPlugin/Admin/Label/Crud/_form.html.twig"
            index:
                icon: partial layout
    type: sylius.resource
    prefix: /admin
